-- Migration: Add section visibility toggle columns
-- Run in Supabase SQL Editor

ALTER TABLE invitations
  ADD COLUMN IF NOT EXISTS show_story BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_program BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_dress_code BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_children_policy BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_hashtag BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_music BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_contact BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_transport BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_accommodation BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_gift_registry BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_faq BOOLEAN DEFAULT TRUE;
